version: '3'

services:

  db: 
    image: postgres:14-alpine
    container_name: greyhat_db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./config/.env.psql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 1s
      retries: 20

  api:
    build:
      context: ./
      target: production
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}