version: '3'

services:

  db: 
    image: postgres:14-alpine
    container_name: greyhat_db-dev
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./config/.env.psql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 1s
      retries: 20
    volumes:
      - db:/var/lib/postgresql/data
    networks: 
      - greyhat

  db_test:
    image: postgres:14-alpine
    container_name: greyhat_db-test
    restart: always
    ports:
      - 5434:5432
    env_file:
      - ./config/.env.psql
    networks: 
      - greyhat-test

  api:
    container_name: greyhat-api-dev
    build:
      context: ./
      target: development
    command: 
      sh -c " sleep 1 && npx prisma migrate deploy && sleep 1 && npm run start:dev"
    ports:
      - 9000:$PORT
    depends_on:
      - db
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./:/usr/src/app
      - ./prisma:/usr/src/app/prisma
      - /usr/src/app/node_modules
    networks:
      - greyhat
      - greyhat-test

volumes:
  db:
    name: greyhat_db-dev

networks:
  greyhat-test:
    driver: bridge
  greyhat:
    driver: bridge

